# Generated by Django 5.0.6 on 2024-05-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidebar', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.EmailField(default='default@example.com', max_length=70, unique=True),
            preserve_default=False,
        ),
    ]
