# Generated by Django 5.0.6 on 2024-05-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sidebar', '0007_alter_user_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_email',
        ),
    ]
