# Generated by Django 5.0.6 on 2024-05-15 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sidebar', '0008_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
    ]
